### ISSUE TITLE
moveGradientsOutsideSymbol doesn't move '<filter>' tag in Firefox

### ISSUE THREAD

**Issue by alxgk** [kisenka/svg-mixer#19]
Hi!
There is no `<filter>` tag in
`const defaultSelector = 'linearGradient, radialGradient, pattern';`
in
`svg-baker/packages/svg-baker-runtime/src/utils/move-gradients-outside-symbol.js`
So filters don't work correctly in Firefox if they are not outside of symbols. Can I add any tags for this option in config or whats the right way to do it ?

**Comment by kisenka** [comment]
Hey Alex! I'll add this tag to default list recently.

**Comment by alxgk** [comment]
Ok, thank you!
