### ISSUE TITLE
Specifying width or height sets it on all nodes

### ISSUE THREAD

**Issue by munik** [kisenka/svg-mixer#28]
We need to set width and height on our SVG icons in order to avoid bad behavior by Internet Explorer. See https://thatemil.com/blog/2015/03/15/sizing-svg-background-images-in-internet-explorer/

However, when I set width and height in the SVG URL querystring, it applies width and height to all nodes, including `RECT`, which mangles the image. I really just want to apply width and height to the `SVG` node.

Would it be an acceptable change to svg-transform-loader to only apply width/height attributes to the SVG node, and not apply it to any other node?

**Comment by kisenka** [comment]
Please read the [docs](https://github.com/kisenka/svg-mixer/tree/master/packages/svg-transform-loader#how-to-pass-transform-parameters)

**Comment by munik** [comment]
Thanks. Sorry. I missed the detail about providing a selector
