### ISSUE TITLE
postcss-move-props-to-bg-image-query double encoding querystring.

### ISSUE THREAD

**Issue by rubylibre** [kisenka/svg-mixer#34]
The plugin create querystring double encoded.

Expected result:
`url("../icons/video.svg?fill=%23ffffff")`

Current result:
`url("../icons/video.svg?fill=%2523ffffff")`

Did some digging and it seems that when adding the querystring to the url the double encoding happens by the [url.setSearch()](https://github.com/kisenka/svg-mixer/blob/master/packages/postcss-move-props-to-bg-image-query/lib/plugin.js#L49) method:
`helper.URIS.forEach(url => url.setSearch(query));`

url.setSearch is method in 'postcss-helpers' lib, which is using URI.js.
Somewhere something changed :).

Hope it helps.

**Comment by kisenka** [comment]
Thanks for reporting! Fixed in `postcss-move-props-to-bg-image-query@0.2.5`.
